// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Actq8Rp4Qn9zUmiNaQoSJgqjbzcDl0k',
    appId: '1:531660640970:web:6a40f90c2031849ef79a33',
    messagingSenderId: '531660640970',
    projectId: 'movie-people-3c362',
    authDomain: 'movie-people-3c362.firebaseapp.com',
    storageBucket: 'movie-people-3c362.firebasestorage.app',
    measurementId: 'G-8NQHKVJGXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2P-oFQBpPVnbgteko5FujHo-CvrJVuec',
    appId: '1:531660640970:android:7a0ede2441981947f79a33',
    messagingSenderId: '531660640970',
    projectId: 'movie-people-3c362',
    storageBucket: 'movie-people-3c362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPOwEo07adD9RIlJuBZOSe_AtT9oPp7s',
    appId: '1:531660640970:ios:55e512d1237c7dd8f79a33',
    messagingSenderId: '531660640970',
    projectId: 'movie-people-3c362',
    storageBucket: 'movie-people-3c362.firebasestorage.app',
    iosBundleId: 'com.scott.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPOwEo07adD9RIlJuBZOSe_AtT9oPp7s',
    appId: '1:531660640970:ios:61033405a36bcdd8f79a33',
    messagingSenderId: '531660640970',
    projectId: 'movie-people-3c362',
    storageBucket: 'movie-people-3c362.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Actq8Rp4Qn9zUmiNaQoSJgqjbzcDl0k',
    appId: '1:531660640970:web:0d43f14f13d46bdaf79a33',
    messagingSenderId: '531660640970',
    projectId: 'movie-people-3c362',
    authDomain: 'movie-people-3c362.firebaseapp.com',
    storageBucket: 'movie-people-3c362.firebasestorage.app',
    measurementId: 'G-2MN9P35B02',
  );
}
